baseURL = "https://code.camdenreslink.com/"
languageCode = "en-us"
title = "Software Developer"
canonifyURLs = true
paginate = 10
summaryLength = 40
pygmentsCodeFences = true
pygmentsUseClasses = false
pygmentsStyle = "monokai"
pygmentsCodefencesGuessSyntax = true
pygmentsOptions= ""